name: Build and push docker image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set commit SHA
        run: echo "COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build --build-arg VERSION=${{ env.VERSION }} --build-arg COMMIT=${{ env.COMMIT }} -t ${{ secrets.ECR_REPOSITORY }}/basic-cli:latest .
          docker push ${{ secrets.ECR_REPOSITORY }}/basic-cli:latest .

      - name: Output Image URI
        run: |
           echo "Pushed image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest"

