name: Build and push docker image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set commit SHA
        run: echo "COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: basic-cli

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "VERSION=${{ env.VERSION }} COMMIT=${{ env.COMMIT }}"
          
      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   with:
      #     version: "~> v2"
      #     args: release --clean
      #     distribution: goreleaser
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
